config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
    :registrations => 'users/registrations'
   }
  root to: "top#index"
  resources :groups do
    resources :reports do
      collection do
        get 'top'
        get 'search'
      end
    end
  end
  resources :attendances, only: [:index,:edit,:update]
  resources :weather, only: :index
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  before_action :set_group
  require "date"
  
  def index
    today = Date.today
    @year = today.year
    @month = today.month
    @day = today.day
    @attendance = Attendance.where(user_id: current_user.id,year: @year,month: @month,day: @day)
  end

  private
  def set_group
    if current_user.groups.ids.blank?
    else
      @group = Group.find(current_user.groups.ids)
      # @group = Group.find_by(params[:group_ids])
    end
  end
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/top/_side.html.erb
 <div class= "side">
    <div class= "side__login">
    
      <% if user_signed_in? && current_user.groups.length > 0 %>
        <div class = "header__right--btn login__name">
          <%= current_user.name %>さんのページ <br>
            <%  current_user.groups.each do |g|%>
              部署: <%=g.name%> <br>
            <%end%>
        </div>
        <%= link_to  new_group_report_path(@group), class:"header__right--btn" do%>
          <i class="fas fa-quidditch "></i>日報作成
        <%end%>
        <%# <%= link_to "部署変更", edit_group_path(@group), method: :get, class:"header__right--btn"%>
        <%= link_to "部署一覧", groups_path(@group) %>
        <%= link_to "レポート検索", search_group_reports_path(@group),class:"header__right--btn"%>
        <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class:"header__right--btn"%>
      <% elsif user_signed_in? && current_user.groups.length == 0 %>
        <div class = "header__right--btn login__name">
          <%= current_user.name%>さんのページ <br>
          <p>下記から部署を登録してください</p>
          <p>↓↓↓</p>
          <%= link_to "部署登録", new_group_path %>
          <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class:"header__right--btn"%>
        </div>
      <% else %>
        <%= link_to "新規登録", new_user_registration_path, class: "header__right--btn" %>
        <p>or</p>
        <%= link_to "ログイン", new_user_session_path, class: "header__right--btn"%>
      <%end%>
    </div>
  </div>

app/views/top/index.html.erb
<div class="main">
  <div class="top">
    <div class="top__contents">
      <% if  current_user.groups.ids.blank?%>
        <div class = "top__contents--btn">
          <%= link_to  new_group_path, class:"link__btn" do%>
            登&emsp;録
          <% end %>
        </div>
      <% else %>
        <div class = "top__contents--btn">
          <%= link_to top_group_reports_path(@group), class:"link__btn" do%>
            日&emsp;報
          <% end%>
        </div>
        <div class = "top__contents--btn">
          <%= link_to search_group_reports_path(@group), class:"link__btn size" do%>
            検&emsp;索
          <% end %>
        </div>
      <% end %>
      <div class = "top__contents--btn">
        <%= link_to edit_attendance_path(@attendance), class:"link__btn" do%>
          勤務表
        <% end%>
      </div>
      <div class = "top__contents--btn">
        <%= link_to weather_index_path, class:"link__btn size",data: {"turbolinks" => false} do%>
          天&emsp;気
        <% end%>
      </div>
    </div>
  </div>
  <%= render partial: "side" %>
</div>