config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
    :registrations => 'users/registrations'
   }
  root to: "top#index"
  resources :groups do
    resources :reports do
      collection do
        get 'top'
        get 'search'
      end
    end
  end
  resources :attendances, only: [:index,:edit,:update]
  resources :weather, only: :index
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_users, foreign_key: 'Group_id'
  # 「group.users」といった呼び出し方ができるようになる
  has_many :users, through: :group_users
  has_many :reports


  validates :name, presence: true, uniqueness: true
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group

  def index
    @groups = Group.all
  end

  def new
    @group_users = GroupUser.new
  end

  def create
    begin
      @group_users = GroupUser.create(group_id:params[:group_id], user_id:params[:user_ids])
      redirect_to root_path, notice: 'グループを作成しました'
    rescue
      render :new
    end
  end

  def edit
    @group_users = GroupUser.find_by(params[:id])
  end

  def update
    if @group.update(group_params)
      redirect_to top_group_reports_path(@group)
    else
      render :edit
    end
  end

  def destroy
    group= Group.find(params[:id])
    group.destroy
    redirect_to groups_path(@group)
  end

  def show
    @group = Group.find(params[:id])
    @group_users = GroupUser.all
  end

  private
  def group_params
    params.require(:group).permit(:name, { :user_ids => [] })
  end

  def set_group
    @group_users = GroupUser.find_by(params[:id])
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_group.html.erb
<div class = "reports">
    <div class="reports__left">
      <%= link_to group_path(group),class: "content__date" do%>
        &emsp;・<%= group.name%>
      <% end %>
    </div>
    <div class="reports__right">
      <div class="reports__right__top">
        <%# <%= link_to "登録", new_group_path(@group), class: "postManage__edit" %>
        <%# <%= link_to "編集", edit_group_path(@group_users), class: "postManage__edit" %>
      </div>
      <div class="reports__right__name">
      </div>
    </div>
  </div>

app/views/groups/edit.html.erb
<div class = "content">
  <div class = "content__title">
    部署番号変更して編集してください。
  </div>
  <div class = "groups__name">
    11.工務課
    12.品質管理課
    13.安全管理課
    14.品質安全課
    15.設備保全課
  </div>

  <%= form_with url: groups_path, html: { method: :post } ,class: :form__group, local: true do |form| %>
    <div class= "form__group--tag">
      <div class= "form__group--name">
        <div class = "input">
          <p>氏名 :</p>
        </div>
        <div class= "new__name">
          <input name= "user_ids" type="hidden" value=<%= current_user.id%>>
          <p class="chat-group-user__name"> <%= current_user.name %></p>
        </div>
      </div>
      <div class= "input">
        <span>担当部署 : </span>
        <input name="group_id" type="integer", placeholder= "番号入力">
      </div>
    </div>
    <%= form.submit 'データ送信', class: :form__btn %>
  <% end %>
</div>

app/views/groups/index.html.erb
<div class="content">
  <% @groups.each do |group| %>
    <%= render partial: "group", locals: { group: group } %>
  <% end %>
</div>

app/views/groups/new.html.erb
<div class = "content">
  <div class = "content__title">
    部署を選択して登録してください。
  </div>

  <%= form_with url: groups_path, html: { method: :post } ,class: :form__group, local: true do |form| %>
    <div class= "form__group--tag">
      <div class= "form__group--name">
        <div class = "input">
          <p>氏名 :</p>
        </div>
        <div class= "new__name">
          <input name= "user_ids" type="hidden" value=<%= current_user.id%>>
          <p class="chat-group-user__name"> <%= current_user.name %></p>
        </div>
      </div>
      <div class= "input">
        <span>担当部署 : </span>
          <%= form.select name= "group_id", class: :group__register  do %>
            <option value= "">------------</option>
            <option value="6">製造課</option>
            <option value="7">工務課</option>
            <option value="8">安全管理課</option>
            <option value="9">品質安全課</option>
            <option value="10">設備保全課</option>
          <% end %>
      </div>
    </div>
    <%= form.submit 'データ送信', class: :form__btn %>
  <% end %>
</div>

app/views/groups/show.html.erb
<div class = "content">
  <div class="content__title">
    部署の詳細
  </div>
  <div class="postManage">
    <%# <%= link_to "登録", new_group_path(@group), class: "postManage__edit" %>
    <%# <%= link_to "編集", edit_group_path(@group_users), class: "postManage__edit" %>
  </div>

  <div class= "form__group">
    <div class= "form__group--tag">
      <div class= "input">
        <span>担当部署:</span>
          <%= @group.name%>
      </div>
      <div class= "form__group--name">
        <div class = "input">
          <p>所属メンバー :</p>
        </div>
        <div class= "input__member">
          <% if @group.users.empty? %>
          <div class= "input__group">
            <p class="chat-group-user__name">メンバーがいません.</p>
          </div>
        <% else %>
          <%  @group.users.each do |user| %>
            <div class= "input__group">
              <li class="chat-group-user__name"> <%= user.name  %></li>
            </div>
          <% end %>
        <% end %>
        </div>
      </div>
    </div>
  </div>
</div>