config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
    :registrations => 'users/registrations'
   }
  root to: "top#index"
  resources :groups do
    resources :reports do
      collection do
        get 'top'
        get 'search'
      end
    end
  end
  resources :attendances, only: [:index,:edit,:update]
  resources :weather, only: :index
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :user
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
  require "date"
  
  def index
    if params[:search] == "次月" then
      @year = params[:year]
      @month = (params[:month].to_i) + 1
      @attendance_list = Attendance.where(user_id: current_user.id,year:params[:year],month:@month)
      if params[:month] == "12" then
        @year = (params[:year].to_i) + 1
        @month = 1
        @attendance_list = Attendance.where(user_id: current_user.id,year:@year,month:@month)
      end
    elsif params[:search] == "前月" then
      @year = params[:year]
      @month = (params[:month].to_i) - 1
      @attendance_list = Attendance.where(user_id: current_user.id,year:params[:year],month:@month)
      if params[:month] == "1" then
        @year = (params[:year].to_i) - 1
        @month = 12
        @attendance_list = Attendance.where(user_id: current_user.id,year:@year,month:@month)
      end
    else
      today = Date.today
      @year = today.year
      @month = today.month
      @attendance_list = Attendance.where(user_id: current_user.id,year:@year,month:@month)
    end
  end

  def edit
    @today = Date.today
    # @today_attendance = Attendance.find_by(days: @today)
    @today_attendance = Attendance.find_by(user_id: current_user.id, year: @today.year,month:@today.month,day:@today.day)
    # 出勤・退勤時間が入力されていれば日本時間でformatを行う
    if !@today_attendance.work_start.nil? then
      @today_attendance_work_start = @today_attendance.work_start.in_time_zone('Tokyo').strftime("%H:%M")
    end
    if !@today_attendance.work_end.nil? then
      @today_attendance_work_end = @today_attendance.work_end.in_time_zone('Tokyo').strftime("%H:%M")
    end
  end

  def update
    @now = Time.new
    today_attendance = Attendance.find(params[:id])
    if params[:commit] == '出勤' then
      today_attendance.work_start = @now
    elsif params[:commit] == '退勤' then
      today_attendance.work_end = @now
    end
    today_attendance.remarks = params[:attendance][:remarks]
    today_attendance.save
    redirect_to action: :edit
  end
end

app/helpers/attendances_helper.rb
module AttendancesHelper
end

app/views/attendances/edit.html.erb
<div class="contents">
  <%= link_to "勤務表一覧",attendances_path, style: "text-decoration:none;" %>
  <div id="contents__today" class="contents__today">
    <%= @today_attendance.year %>年<%= @today_attendance.month %>月<%= @today_attendance.day %>日
  </div>
  <%= form_with model: @today_attendance do |f| %>
    <div class="contents__btn_list">
      <div>
        <%= f.submit "出勤", class: :contents__btn_list__work_start, id: :work_start__btn %>
        <p id="work_start__hours" class="contents__btn_list__push_time_now"><%= @today_attendance_work_start %></p>
      </div>
      <div>
        <%= f.submit "退勤", class: :contents__btn_list__work_end, id: :work_end__btn %>
        <p id="work_end__hours" class="contents__btn_list__push_time_now"><%= @today_attendance_work_end %></p>
      </div>
    </div>
    <div class="contents__remarks_area">
      <%= f.text_area :remarks, class: :contents__remarks_area__remarks %>
    </div>
  <% end %>
</div>

app/views/attendances/index.html.erb
<div class="title"><span id="year"><%= @year %></span>年<span id="month"><%= @month %></span>月の勤務表</div>

<table class="list">
  <tr class="list__headers">
    <th class="list__headers__header">日付</th>
    <th class="list__headers__header">出勤</th>
    <th class="list__headers__header">退勤</th>
    <th class="list__headers__header">備考</th>
  </tr>

  <% @attendance_list.each do |attend| %>
    <tr class="list__contents">
      <td><%= attend.year %>年<%= attend.month %>月<%= attend.day %>日</td>
      <% if attend.work_start.nil? %>
        <td class="list__contents__performance"><input type="text" disabled="disabled" value="<%= attend.work_start %>"></td>
      <% else %>
        <td class="list__contents__performance"><input type="text" disabled="disabled" value="<%= attend.work_start.in_time_zone('Tokyo').strftime("%H:%M") %>"></td>
      <% end %>
      <% if attend.work_end.nil? %>
        <td class="list__contents__performance"><input type="text" disabled="disabled" value="<%= attend.work_end %>"></td>
      <% else %>
        <td class="list__contents__performance"><input type="text" disabled="disabled" value="<%= attend.work_end.in_time_zone('Tokyo').strftime("%H:%M") %>"></td>
      <% end %>
      <td class="list__contents__performance"><input type="text" disabled="disabled" value="<%= attend.remarks %>"></td>
    </tr>
  <% end %>
</table>

<%= form_tag(attendances_path,:method => 'get') do %>
  <%= hidden_field_tag 'year', "#{@year}"%>
  <%= hidden_field_tag 'month', "#{@month}"%>
  <div class="btn_field" style="display:flex;justify-content:space-around;padding:30px 0 60px;">
    <%= submit_tag '前月', name: "search", style: "width:60px;", id: "last" %>
    <%= submit_tag '次月', name: "search", style: "width:60px;", id: "next" %>
  </div>
<% end %>