config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
    :registrations => 'users/registrations'
   }
  root to: "top#index"
  resources :groups do
    resources :reports do
      collection do
        get 'top'
        get 'search'
      end
    end
  end
  resources :attendances, only: [:index,:edit,:update]
  resources :weather, only: :index
end

app/models/report.rb
class Report < ApplicationRecord
  belongs_to :group
  belongs_to :user

  validates :date, :text, presence: true

  # 引数で渡されるsearchの中身に何もなければ全ての投稿を取得
  def self.search(search)
    return Report.all unless search
    Report.where('date LIKE(?)', "%#{search}%")
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :set_group
  
  def top
    today = Date.today
    @year = today.year
    @month = today.month
    @day = today.day
    @attendance = Attendance.where(user_id: current_user.id,year: @year,month: @month,day: @day)
  end

  # 過去履歴
  def index
    @reports = Report.new
    @reports = @group.reports.includes(:user).order("created_at desc")
  end

  def new
    @report = Report.new
    # @group = Group.find_by(params[:group_ids])
  end

  def create
    @report = @group.reports.new(report_params)
    if @report.save
      redirect_to group_reports_path(@report), notice: 'メッセージが送信されました'
    else
      @reports = @group.reports.includes(:user)
      flash.now[:alert] = 'メッセージを入力してください。'
      render :new
    end
  end

  def show
    @report = Report.find(params[:id])
  end

  def edit
    @report = Report.find(params[:id])
  end

  def update
    report = Report.find(params[:id])
    report.update(report_params)
    redirect_to  group_reports_path(current_user.groups.ids)
  end

  def destroy
    report = Report.find(params[:id])
    report.destroy
    redirect_to group_reports_path(current_user.groups.ids)
  end

  def search
    @reports = Report.search(params[:keyword]).order("created_at desc").includes(:user)
  end

  private
  def report_params
    params.require(:report).permit(:date, :text).merge(user_id: current_user.id)
  end

  def set_group
    # @group = Group.find_by(params[:group_id])
    @group = Group.find(current_user.groups.ids.first)
  end

end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/reports/_report.html.erb
<div class = "reports">
  <div class="reports__left">
    <%= link_to group_report_path(@group,report) do %>
      <%=report.date%>
    <% end %>
  </div>
  <div class="reports__right">
    <div class="reports__right__top">
      <%= report.group.name %>
    </div>
    <div class="reports__right__name">
      <%= report.user.name %>
    </div>
  </div>
</div>

app/views/reports/edit.html.erb
<div class="content">
  <div class="content__title">
    記事編集
  </div>

  <%= form_with(model: [@group,@report],class: :form) do |form| %>
    <%= form.date_field :date, value: (Time.now.strftime("%Y-%m-%d"))%>
    <%= form.text_area :text, placeholder: :日報記事内容, class: :form__text , content__titles: "10", id: "content" %>
    <%= form.submit '記事送信', class: :form__btn %>
  <% end %>
</div>

app/views/reports/index.html.erb
<div class="content">
  <% @reports.each do |report| %>
    <%= render partial: "report", locals: { report: report } %>
  <% end %>
</div>

app/views/reports/new.html.erb
<div class = "content">
  <div class = "contens">
    <div class="content__title">
      新規記事の作成
    </div>

    <%= form_with(model: [@group,@report],class: :form) do |form| %>
      <%= form.date_field :date, max: "2030-1-1", min:"1950-1-1",value: (Time.now.strftime("%Y-%m-%d"))%>
      <%= form.text_area :text, placeholder: :日報記事内容, class: :form__text , content__titles: "10", id: "content" %>
      <%= form.submit '記事送信', class: :form__btn %>
    <% end %>
  </div>
</div>

app/views/reports/search.html.erb
<div class="content">
  <%= form_with(url: search_group_reports_path, local: true, method: :get, class: "search-form") do |form| %>
    <%= form.text_field :keyword, placeholder: "レポートの日付検索", class: "search-input" %>
    <%= form.submit "検索", class: "search-btn" %>
  <% end %>
  <% @reports.each do |report| %>
    <%= render partial: "report", locals: { report: report } %>
  <% end %>
</div>

app/views/reports/show.html.erb
<div class = "content">
  <div class="content__title">
    記事の詳細
  </div>
  <div class="postManage">
    <%= link_to "編集", edit_group_report_path(@report.id), class: "postManage__edit" %>
    <%= link_to "削除", group_report_path(@report), method: :delete, class: "postManage__delete", data:{confirm: "削除しますか？"}  %>
  </div>

  <div class= "form">
    <p>
      <%= @report.date %>
    </p>
    <div class= "form__text">
      <%= @report.text %>
    </div>
  </div>
</div>

app/views/reports/top.html.erb
<div class="main">
  <div class="top">
    <div class="top__contents">
      <div class = "top__contents--btn">
        <%= link_to new_group_report_path(@group), class:"link__btn" do%>
          新規作成
        <% end%>
      </div>
      <div class = "top__contents--btn">
      <%= link_to group_reports_path(@group), class:"link__btn" do%>
        <%# <%= link_to group_reports_path(@group), class:"link__btn" do%>
          過去履歴
        <% end%>
      </div>
    </div>
  </div>
  <%= render partial: "top/side" %>
</div>